[package]
name = "llvm2cretonne-tools"
version = "0.0.0"
authors = ["The Cretonne Project Developers"]
publish = false
license = "MIT/Apache-2.0"

[[bin]]
name = "llvm2cretonne"
path = "src/llvm2cretonne.rs"

# Temporarily pin faerie to a specific revision because the mach changes
# had compilation errors which I haven't investigated yet.
[dependencies]
cretonne-llvm = { path = "lib/llvm" }
cretonne = { git = "https://github.com/stoklund/cretonne.git"}
cretonne-reader = { git = "https://github.com/stoklund/cretonne.git"}
docopt = "0.8.0"
serde = "1.0.8"
serde_derive = "1.0.8"
term = "0.4.6"
faerie = { git = "https://github.com/m4b/faerie", rev = "f70382dafeccc7bbb36c730d104a32ba45d41bf7" }

[workspace]
